version: '3'

services:
  database:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pA**w0rd
      - POSTGRES_DB=test